/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlowRouteRouteImport } from './routes/slow-route'
import { Route as FastRouteRouteImport } from './routes/fast-route'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthedConvexRouteRouteImport } from './routes/_authed/convex-route'
import { Route as AuthedAuthRouteRouteImport } from './routes/_authed/auth-route'

const SlowRouteRoute = SlowRouteRouteImport.update({
  id: '/slow-route',
  path: '/slow-route',
  getParentRoute: () => rootRouteImport,
} as any)
const FastRouteRoute = FastRouteRouteImport.update({
  id: '/fast-route',
  path: '/fast-route',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedConvexRouteRoute = AuthedConvexRouteRouteImport.update({
  id: '/convex-route',
  path: '/convex-route',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthRouteRoute = AuthedAuthRouteRouteImport.update({
  id: '/auth-route',
  path: '/auth-route',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fast-route': typeof FastRouteRoute
  '/slow-route': typeof SlowRouteRoute
  '/auth-route': typeof AuthedAuthRouteRoute
  '/convex-route': typeof AuthedConvexRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fast-route': typeof FastRouteRoute
  '/slow-route': typeof SlowRouteRoute
  '/auth-route': typeof AuthedAuthRouteRoute
  '/convex-route': typeof AuthedConvexRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/fast-route': typeof FastRouteRoute
  '/slow-route': typeof SlowRouteRoute
  '/_authed/auth-route': typeof AuthedAuthRouteRoute
  '/_authed/convex-route': typeof AuthedConvexRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fast-route'
    | '/slow-route'
    | '/auth-route'
    | '/convex-route'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fast-route'
    | '/slow-route'
    | '/auth-route'
    | '/convex-route'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/fast-route'
    | '/slow-route'
    | '/_authed/auth-route'
    | '/_authed/convex-route'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  FastRouteRoute: typeof FastRouteRoute
  SlowRouteRoute: typeof SlowRouteRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slow-route': {
      id: '/slow-route'
      path: '/slow-route'
      fullPath: '/slow-route'
      preLoaderRoute: typeof SlowRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-route': {
      id: '/fast-route'
      path: '/fast-route'
      fullPath: '/fast-route'
      preLoaderRoute: typeof FastRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/convex-route': {
      id: '/_authed/convex-route'
      path: '/convex-route'
      fullPath: '/convex-route'
      preLoaderRoute: typeof AuthedConvexRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/auth-route': {
      id: '/_authed/auth-route'
      path: '/auth-route'
      fullPath: '/auth-route'
      preLoaderRoute: typeof AuthedAuthRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuthRouteRoute: typeof AuthedAuthRouteRoute
  AuthedConvexRouteRoute: typeof AuthedConvexRouteRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuthRouteRoute: AuthedAuthRouteRoute,
  AuthedConvexRouteRoute: AuthedConvexRouteRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  FastRouteRoute: FastRouteRoute,
  SlowRouteRoute: SlowRouteRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
